<!--
  AttentionTrace - the worked example, drawn.

  Every number comes from composables/useDeckNumbers.ts, generated by
  scripts/verify-attention.py and cross-checked against PyTorch's
  F.scaled_dot_product_attention in float64.
    IF A NUMBER HERE DISAGREES WITH THAT SCRIPT, THIS FILE IS WRONG.

  READING CONVENTIONS (consistent across every stage)
    a row            = one token
    purple cells     = Query   "what am I looking for?"
    orange cells     = Key     "what do I have?"
    blue cells       = Value   "what will I pass on?"
    grey cells       = x, the token's own vector, and the W matrices
    a GREY cell is a learned parameter or raw input; a COLOURED cell is
    something computed from it. That distinction is the whole reason the
    three W matrices are drawn in grey.

  THE DIMMING TRICK (stage="blend")
  Each value vector is drawn at opacity equal to its attention weight, so
  v_dropped at 0.10 is a ghost beside v_glass at 0.85. This is the best
  available picture of "weighted blend, not winner-takes-all", and it is
  doing real pedagogical work: it is the visual repair for the spotlight
  misconception. Nothing is ever fully transparent, because no weight is
  ever zero.

  CLICK CONTRACT: none. Driven entirely by `stage`:

  BEWARE `opacity` AS AN ATTRIBUTE.
  Slidev runs UnoCSS with the attributify preset, which reads bare HTML
  attributes as utility classes. `opacity="1"` is therefore parsed as the
  utility `opacity-1`, and on the Tailwind scale that means ONE PER CENT - so
  a fully opaque element renders invisible, and only when the value is exactly
  1. Every opacity here is set through `:style` for that reason. Do not
  "simplify" it back to an attribute.

    'setup'  the three tokens as plain vectors
    'qkv'    each one projected into a query, a key and a value
    'blend'  the weighted sum, with values dimmed by weight
-->

<script setup lang="ts">
import { computed } from 'vue'
import { N } from '../composables/useDeckNumbers'

const props = withDefaults(defineProps<{
  stage?: 'setup' | 'qkv' | 'blend'
  row?: number
  compact?: boolean
}>(), { stage: 'qkv', row: 2, compact: false })

const w = N.worked
const tokens = [...w.tokens]

const CW = 36, CH = 30, GAP = 3
const ROW_Y = [78, 150, 222]
const X_LBL = 16
const X_X = 96
const X_Q = 286
const X_K = 400
const X_V = 514
const X_W = 654
const W_SVG = 920
const H_SVG = 300

const showQKV = computed(() => props.stage !== 'setup')
const showBlend = computed(() => props.stage === 'blend')

const weights = computed(() => (w.weights as unknown as number[][])[props.row])

const grp = (arr: readonly number[], x: number) =>
  arr.map((v, i) => ({ v, x: x + i * (CW + GAP) }))

const widthOf = (n: number) => n * CW + (n - 1) * GAP

// Value opacity == attention weight. Floored so nothing vanishes: no
// attention weight is ever actually zero, and the picture must not lie.
const vOpacity = (i: number) => showBlend.value ? 0.15 + weights.value[i] * 0.85 : 1
</script>

<template>
  <div class="trace" :class="{ 'is-compact': compact }">
    <svg :viewBox="`0 0 ${W_SVG} ${H_SVG}`" xmlns="http://www.w3.org/2000/svg">
      <!-- column headings -->
      <text :x="X_X + widthOf(4) / 2" y="46" class="hd grey">the word&#39;s own vector</text>
      <template v-if="showQKV">
        <text :x="X_Q + widthOf(2) / 2" y="46" class="hd q">Query</text>
        <text :x="X_K + widthOf(2) / 2" y="46" class="hd k">Key</text>
        <text :x="X_V + widthOf(2) / 2" y="46" class="hd v">Value</text>
        <text :x="X_Q + widthOf(2) / 2" y="30" class="sub q">what I&#39;m looking for</text>
        <text :x="X_K + widthOf(2) / 2" y="30" class="sub k">what I have</text>
        <text :x="X_V + widthOf(2) / 2" y="30" class="sub v">what I pass on</text>
      </template>
      <text v-if="showBlend" :x="X_W + 58" y="46" class="hd p">attention</text>

      <g v-for="(t, r) in tokens" :key="t">
        <text :x="X_LBL" :y="ROW_Y[r] + 20" class="tok"
              :class="{ lit: showBlend && r === row }">{{ t }}</text>

        <!-- x -->
        <g v-for="(c, i) in grp(w.x[r], X_X)" :key="'x' + i">
          <rect :x="c.x" :y="ROW_Y[r]" :width="CW" :height="CH" rx="4"
                fill="var(--ann-paper-raised)" stroke="var(--ann-line)" stroke-width="1.5" />
          <text :x="c.x + CW / 2" :y="ROW_Y[r] + 20" class="cell">{{ c.v }}</text>
        </g>

        <template v-if="showQKV">
          <text :x="X_X + widthOf(4) + 16" :y="ROW_Y[r] + 20" class="op">&#8594;</text>

          <g v-for="(c, i) in grp(w.q[r], X_Q)" :key="'q' + i">
            <rect :x="c.x" :y="ROW_Y[r]" :width="CW" :height="CH" rx="4"
                  fill="var(--qkv-query-soft)" stroke="var(--qkv-query)" stroke-width="2" />
            <text :x="c.x + CW / 2" :y="ROW_Y[r] + 20" class="cell q">{{ c.v }}</text>
          </g>

          <g v-for="(c, i) in grp(w.k[r], X_K)" :key="'k' + i">
            <rect :x="c.x" :y="ROW_Y[r]" :width="CW" :height="CH" rx="4"
                  fill="var(--qkv-key-soft)" stroke="var(--qkv-key)" stroke-width="2" />
            <text :x="c.x + CW / 2" :y="ROW_Y[r] + 20" class="cell k">{{ c.v }}</text>
          </g>

          <g v-for="(c, i) in grp(w.v[r], X_V)" :key="'v' + i" :style="{ opacity: vOpacity(r) }">
            <rect :x="c.x" :y="ROW_Y[r]" :width="CW" :height="CH" rx="4"
                  fill="var(--qkv-value-soft)" stroke="var(--qkv-value)" stroke-width="2" />
            <text :x="c.x + CW / 2" :y="ROW_Y[r] + 20" class="cell v">{{ c.v }}</text>
          </g>
        </template>

        <!-- the scores / weights for the focused row -->
        <template v-if="showBlend">
          <text :x="X_W" :y="ROW_Y[r] + 20" class="arrowto">{{ tokens[row] }} &#8594; {{ t }}</text>
          <rect :x="X_W + 96" :y="ROW_Y[r] + 2" :width="54" :height="CH - 4" rx="4"
                fill="var(--ann-indigo-soft)" stroke="var(--ann-indigo)" stroke-width="1.5" />
          <text :x="X_W + 123" :y="ROW_Y[r] + 20" class="cell p">{{ weights[r].toFixed(2) }}</text>
        </template>
      </g>

      <!-- the blend result -->
      <template v-if="showBlend">
        <line :x1="X_V - 14" :y1="ROW_Y[2] + CH + 16" :x2="X_V + widthOf(2) + 14"
              :y2="ROW_Y[2] + CH + 16" stroke="var(--ann-ink-soft)" stroke-width="1.5" />
        <text :x="X_V + widthOf(2) / 2" :y="ROW_Y[2] + CH + 42" class="sum">
          add them up, each weighted by its number
        </text>
        <g v-for="(c, i) in grp(w.output[row], X_V)" :key="'z' + i">
          <rect :x="c.x" :y="ROW_Y[2] + CH + 52" :width="CW" :height="CH" rx="4"
                fill="var(--ann-indigo-soft)" stroke="var(--ann-indigo)" stroke-width="2.5" />
          <text :x="c.x + CW / 2" :y="ROW_Y[2] + CH + 72" class="cell p">{{ c.v.toFixed(2) }}</text>
        </g>
        <text :x="X_V + widthOf(2) + 24" :y="ROW_Y[2] + CH + 72" class="zlbl">
          the new vector for &#8220;{{ tokens[row] }}&#8221;
        </text>
      </template>
    </svg>
  </div>
</template>

<style scoped>
.trace svg { width: 100%; max-height: 42vh; display: block; }
.trace.is-compact svg { max-height: 34vh; }

.cell {
  font-family: 'JetBrains Mono', ui-monospace, monospace;
  font-variant-numeric: tabular-nums;
  font-size: 15px;
  fill: var(--ann-ink);
  text-anchor: middle;
}
.cell.q { fill: var(--qkv-query); font-weight: 600; }
.cell.k { fill: var(--qkv-key); font-weight: 600; }
.cell.v { fill: var(--qkv-value); font-weight: 600; }
.cell.p { fill: var(--ann-indigo); font-weight: 600; }

.tok {
  font-family: 'JetBrains Mono', ui-monospace, monospace;
  font-size: 15px;
  fill: var(--ann-ink);
}
.tok.lit { fill: var(--ann-ember); font-weight: 700; }

.hd {
  font-family: 'Space Grotesk', ui-sans-serif, sans-serif;
  font-size: 14px;
  font-weight: 600;
  text-anchor: middle;
}
.hd.q { fill: var(--qkv-query); }
.hd.k { fill: var(--qkv-key); }
.hd.v { fill: var(--qkv-value); }
.hd.p { fill: var(--ann-indigo); }
.hd.grey { fill: var(--ann-ink-soft); }

.sub {
  font-family: 'JetBrains Mono', ui-monospace, monospace;
  font-size: 9.5px;
  text-anchor: middle;
  opacity: 0.85;
}
.sub.q { fill: var(--qkv-query); }
.sub.k { fill: var(--qkv-key); }
.sub.v { fill: var(--qkv-value); }

.op { font-size: 19px; fill: var(--ann-muted); text-anchor: middle; }

.arrowto, .sum, .zlbl {
  font-family: 'JetBrains Mono', ui-monospace, monospace;
  font-size: 11.5px;
  fill: var(--ann-ink-soft);
}
.sum { text-anchor: middle; }
.zlbl { fill: var(--ann-indigo); font-size: 12.5px; }
</style>
