<!--
  AttentionHeat - the attention matrix, as a real figure.

  Numbers come from composables/useDeckNumbers.ts, generated by
  scripts/verify-attention.py.  IF A NUMBER HERE DISAGREES, THIS FILE IS WRONG.

  TWO DESIGN DECISIONS THAT ARE NOT ARBITRARY

  1. CIRCLES, NOT FILLED SQUARES. Radius is set so that AREA is proportional
     to the weight, and colour intensity tracks it too. That is deliberate
     redundancy: a projector in a lit hall delivers maybe 15:1 contrast
     against a laptop's 1000:1, and the mid-range of any colour ramp is the
     first thing it destroys. Area survives what colour does not.

  2. THE SCALE CHANGES WITH THE STAGE, because the data changes.
     Raw and scaled SCORES are signed - a negative score means "these two
     actively disagree" - so those stages get a DIVERGING scale: teal for
     positive, ember for negative, with a neutral middle. That matches the
     deck's grammar, where ember has meant "opposing" since chapter 1.
     Softmax WEIGHTS are all >= 0 and sum to 1. There is no polarity and no
     meaningful midpoint, so those stages get a SEQUENTIAL scale: one hue,
     monotonic. Using a diverging scale there would invent a distinction that
     does not exist, and using a sequential one on the scores would hide a
     distinction that does.

  Masked cells are a STATE, not a value of zero - they render as an empty
  cell with a dash, never as "very dark". Drawing them as 0.00 would suggest
  the model considered them and scored them low. It never saw them.

  CLICK CONTRACT: none. Driven entirely by the `stage` prop.

  BEWARE `opacity` AS AN ATTRIBUTE.
  Slidev runs UnoCSS with the attributify preset, which reads bare HTML
  attributes as utility classes. `opacity="1"` is therefore parsed as the
  utility `opacity-1`, and on the Tailwind scale that means ONE PER CENT - so
  a fully opaque element renders invisible, and only when the value is exactly
  1. Every opacity here is set through `:style` for that reason. Do not
  "simplify" it back to an attribute.

    stage = 'raw'     integer dot products, before any scaling
            'scaled'  after dividing by sqrt(d_k)
            'softmax' the attention weights (rows sum to 1)
            'causal'  the same, with the future masked out
-->

<script setup lang="ts">
import { computed } from 'vue'
import { N } from '../composables/useDeckNumbers'

const props = withDefaults(defineProps<{
  stage?: 'raw' | 'scaled' | 'softmax' | 'causal'
  highlightRow?: number
  compact?: boolean
}>(), { stage: 'softmax', compact: false })

const tokens = [...N.worked.tokens]
const n = tokens.length

const matrix = computed<number[][]>(() => {
  const w = N.worked
  if (props.stage === 'raw') return w.scores as unknown as number[][]
  if (props.stage === 'scaled') return w.scaled as unknown as number[][]
  if (props.stage === 'causal') return w.causalWeights as unknown as number[][]
  return w.weights as unknown as number[][]
})

const isWeights = computed(() => props.stage === 'softmax' || props.stage === 'causal')
const masked = (r: number, c: number) => props.stage === 'causal' && c > r

// Geometry. Generous cells: 3 tokens is few enough to draw big, and big is
// the entire requirement for the back row.
const CELL = 74
const LEFT = 104
const TOP = 46
const W = LEFT + n * CELL + 16
const H = TOP + n * CELL + 34

const maxAbs = computed(() => Math.max(...matrix.value.flat().map(Math.abs), 1e-9))

function radius(v: number) {
  const frac = isWeights.value ? v : Math.abs(v) / maxAbs.value
  return 4 + Math.sqrt(Math.max(frac, 0)) * (CELL / 2 - 9)   // area ∝ magnitude
}
function tint(v: number) {
  const frac = isWeights.value ? v : Math.abs(v) / maxAbs.value
  return 0.12 + Math.max(frac, 0) * 0.88
}
// Sequential for weights; diverging for signed scores.
const hueOf = (v: number) =>
  isWeights.value || v >= 0 ? 'var(--ann-circuit)' : 'var(--ann-ember)'
const fmt = (v: number) => isWeights.value ? v.toFixed(2) : (props.stage === 'raw' ? v.toFixed(0) : v.toFixed(2))
</script>

<template>
  <div class="heat" :class="{ 'is-compact': compact }">
    <svg :viewBox="`0 0 ${W} ${H}`" xmlns="http://www.w3.org/2000/svg">
      <text :x="LEFT + (n * CELL) / 2" :y="18" class="axis">attending to &#8594;</text>
      <text v-for="(t, c) in tokens" :key="'c' + t"
            :x="LEFT + c * CELL + CELL / 2" :y="TOP - 10" class="head">{{ t }}</text>

      <text :x="14" :y="TOP + (n * CELL) / 2" class="axis side"
            :transform="`rotate(-90 14 ${TOP + (n * CELL) / 2})`">this word</text>

      <g v-for="(row, r) in matrix" :key="'r' + r">
        <text :x="LEFT - 12" :y="TOP + r * CELL + CELL / 2 + 5" class="head row"
              :class="{ lit: highlightRow === r }">{{ tokens[r] }}</text>

        <g v-for="(val, c) in row" :key="'c' + c">
          <rect :x="LEFT + c * CELL" :y="TOP + r * CELL" :width="CELL" :height="CELL"
                fill="none" stroke="var(--ann-line)" stroke-width="1" />

          <template v-if="masked(r, c)">
            <line :x1="LEFT + c * CELL + CELL / 2 - 11" :y1="TOP + r * CELL + CELL / 2"
                  :x2="LEFT + c * CELL + CELL / 2 + 11" :y2="TOP + r * CELL + CELL / 2"
                  stroke="var(--ann-ember)" stroke-width="3" stroke-linecap="round" />
          </template>

          <template v-else>
            <circle :cx="LEFT + c * CELL + CELL / 2" :cy="TOP + r * CELL + CELL / 2"
                    :r="radius(val)" :fill="hueOf(val)" :style="{ opacity: tint(val) }" />
            <text :x="LEFT + c * CELL + CELL / 2" :y="TOP + r * CELL + CELL / 2 + 5"
                  class="val" :class="{ inv: tint(val) > 0.55 }">{{ fmt(val) }}</text>
          </template>
        </g>

        <rect v-if="highlightRow === r"
              :x="LEFT - 2" :y="TOP + r * CELL - 2" :width="n * CELL + 4" :height="CELL + 4"
              fill="none" stroke="var(--ann-ember)" stroke-width="3" rx="4" />
      </g>

      <text v-if="!isWeights" :x="W / 2" :y="H - 10" class="note">
        circle size = how strong &#183;
        <tspan fill="var(--ann-circuit)">teal = agree</tspan>,
        <tspan fill="var(--ann-ember)">ember = actively disagree</tspan>
      </text>
      <text v-else-if="stage === 'causal'" :x="W / 2" :y="H - 10" class="note">
        &#8212; = never scored. Set to &#8722;&#8734; before softmax, so it becomes exactly 0 and the row still sums to 1.
      </text>
      <text v-else-if="isWeights" :x="W / 2" :y="H - 10" class="note">
        every row sums to 1 &#183; every entry is strictly greater than zero
      </text>
    </svg>
  </div>
</template>

<style scoped>
.heat svg { width: 100%; max-height: 40vh; display: block; margin: 0 auto; }
.heat.is-compact svg { max-height: 27vh; }

text { text-anchor: middle; }

.head {
  font-family: 'JetBrains Mono', ui-monospace, monospace;
  font-size: 15px;
  fill: var(--ann-ink);
}
.head.row { text-anchor: end; }
.head.row.lit { fill: var(--ann-ember); font-weight: 700; }

.axis {
  font-family: 'JetBrains Mono', ui-monospace, monospace;
  font-size: 11px;
  letter-spacing: 0.08em;
  fill: var(--ann-muted);
}

.val {
  font-family: 'JetBrains Mono', ui-monospace, monospace;
  font-variant-numeric: tabular-nums;
  font-size: 13px;
  fill: var(--ann-ink);
}
/* Once the circle is dark enough, ink-on-teal fails; flip to paper. */
.val.inv { fill: var(--ann-paper); font-weight: 600; }

.note {
  font-family: 'JetBrains Mono', ui-monospace, monospace;
  font-size: 10.5px;
  fill: var(--ann-muted);
}
</style>
