<!--
  BpeTrace - byte-pair encoding, one merge at a time.

  Numbers come from composables/useDeckNumbers.ts (N.bpe), generated by
  scripts/verify-attention.py section 6.  IF A NUMBER HERE DISAGREES, THIS
  FILE IS WRONG.

  LEFT: the toy corpus, each word drawn as its current chunks, with how often
  the word occurs. RIGHT: the pair counts that decide the NEXT merge, winner
  highlighted. BOTTOM: the vocabulary so far.

  COLOUR HERE CARRIES IDENTITY, unlike TokenStrip, where the hues are only a
  partition marker. The same chunk gets the same hue in every word, so when
  "ing" is born it lights up in reading, ring and sing at once - which is the
  whole point of BPE: shared pieces.

  CLICK CONTRACT: none. Drive `step` from the slide (0 = raw characters,
  7 = after every merge). `unseen` swaps the right panel for the two words the
  tokenizer never saw, tokenized by replaying the merges.
-->

<script setup lang="ts">
import { computed } from 'vue'
import { N } from '../composables/useDeckNumbers'

const props = withDefaults(defineProps<{
  step?: number
  unseen?: boolean
  compact?: boolean
}>(), { step: 0, unseen: false, compact: false })

type Step = { pair: string[], merged: string, count: number, top: [string, number][], words: Record<string, string[]> }
const steps = N.bpe.steps as unknown as Step[]
const corpus = N.bpe.corpus as unknown as Record<string, number>
const unseenWords = N.bpe.unseen as unknown as Record<string, string[]>

const s = computed(() => Math.max(0, Math.min(props.step, steps.length)))

const words = computed(() => Object.keys(corpus).map(w => ({
  word: w,
  count: corpus[w],
  chunks: s.value === 0 ? w.split('') : steps[s.value - 1].words[w],
})))

const next = computed(() => (s.value < steps.length ? steps[s.value] : null))
const merges = computed(() => steps.slice(0, s.value).map(st => st.merged))
const baseChars = [...new Set(Object.keys(corpus).join('').split(''))].sort()

// Pale hues, pinned light in both themes (dark text on them).
const HUES = ['#bae6fd', '#fde68a', '#bbf7d0', '#fed7aa', '#e9d5ff', '#a5f3fc',
  '#fecdd3', '#d9f99d', '#c7d2fe', '#fbcfe8', '#99f6e4', '#fef08a']
const MERGED = ['#fcd34d', '#86efac', '#f9a8d4', '#93c5fd', '#fdba74', '#c4b5fd', '#5eead4']
function hueOf(chunk: string) {
  const mi = steps.findIndex(st => st.merged === chunk)
  if (mi >= 0) return MERGED[mi % MERGED.length]
  return HUES[baseChars.indexOf(chunk) % HUES.length]
}
const isNew = (chunk: string) => s.value > 0 && steps[s.value - 1].merged === chunk
</script>

<template>
  <div class="bpe" :class="{ 'is-compact': compact }">
    <div class="corpus">
      <div class="hdr">corpus <span class="dim">(word × times seen)</span></div>
      <div v-for="w in words" :key="w.word" class="row">
        <span class="chunks">
          <span v-for="(c, i) in w.chunks" :key="i" class="chunk"
                :class="{ fresh: isNew(c) }" :style="{ background: hueOf(c) }">{{ c }}</span>
        </span>
        <span class="cnt">× {{ w.count }}</span>
        <span class="ntok">{{ w.chunks.length }} tok</span>
      </div>
    </div>

    <div class="side">
      <template v-if="!unseen">
        <div class="hdr">{{ next ? `merge ${s + 1}: count every adjacent pair` : 'done — 7 merges' }}</div>
        <div v-if="next" class="pairs">
          <div v-for="(p, i) in next.top" :key="p[0]" class="pair" :class="{ win: i === 0 }">
            <span class="pname">{{ i === 0 ? next.pair.join(' + ') : p[0] }}</span>
            <span class="pbar" :style="{ width: (p[1] / next.top[0][1]) * 7 + 'em' }"></span>
            <span class="pc">{{ p[1] }}</span>
          </div>
          <div class="rule">winner &#8594; new token <b>{{ next.merged }}</b></div>
        </div>
        <div v-else class="pairs done">Every word is now 1–3 tokens. Keep going and you reach a real vocabulary: 50,257 for GPT-2.</div>
      </template>
      <template v-else>
        <div class="hdr">words it has <b>never seen</b></div>
        <div v-for="(chunks, w) in unseenWords" :key="w" class="row">
          <span class="chunks">
            <span v-for="(c, i) in chunks" :key="i" class="chunk" :style="{ background: hueOf(c) }">{{ c }}</span>
          </span>
        </div>
        <div class="rule">replay the merges in order &#8594; no <code>&lt;UNK&gt;</code> needed</div>
      </template>
    </div>

    <div class="vocab">
      <span class="hdr inline">vocabulary</span>
      <span class="vchip base">{{ baseChars.length }} letters</span>
      <span v-for="m in merges" :key="m" class="vchip" :style="{ background: hueOf(m) }">{{ m }}</span>
    </div>
  </div>
</template>

<style scoped>
.bpe {
  display: grid; grid-template-columns: 1.15fr 1fr; gap: 0.4em 1.6em;
  font-family: 'JetBrains Mono', ui-monospace, monospace;
}
.hdr { font-size: 0.72rem; letter-spacing: 0.08em; text-transform: uppercase; color: var(--ann-muted); margin-bottom: 0.3em; }
.hdr b { color: var(--ann-ember); }
.hdr.inline { margin: 0 0.4em 0 0; }
.dim { text-transform: none; letter-spacing: 0; }
.row { display: flex; align-items: center; gap: 0.7em; margin: 0.18em 0; }
.chunks {
  display: inline-flex; font-size: 22px; line-height: 1.3; color: #111827;
  background: #f8fafc; border: 1px solid #e5e7eb; border-radius: 6px; padding: 2px 8px; min-width: 6.4em;
}
.bpe.is-compact .chunks { font-size: 19px; }
.chunk { border-radius: 0; padding: 0 1px; }
.chunk.fresh { outline: 2.5px solid var(--ann-ember); outline-offset: -1px; font-weight: 700; }
.cnt { font-size: 0.85rem; color: var(--ann-indigo); width: 2.6em; }
.ntok { font-size: 0.72rem; color: var(--ann-muted); }
.pairs { display: flex; flex-direction: column; gap: 0.25em; }
.pair { display: flex; align-items: center; gap: 0.5em; font-size: 0.95rem; color: var(--ann-ink-soft); }
.pname { width: 6.5em; text-align: right; }
.pbar { height: 0.8em; background: var(--ann-line); border-radius: 2px; }
.pc { font-variant-numeric: tabular-nums; }
.pair.win { color: var(--ann-ember); font-weight: 700; }
.pair.win .pbar { background: var(--ann-ember); }
.rule { margin-top: 0.35em; font-size: 0.85rem; color: var(--ann-ink-soft); }
.rule b { color: var(--ann-circuit); font-size: 1.05rem; }
.done { font-family: 'Inter', sans-serif; font-size: 0.9rem; color: var(--ann-ink-soft); max-width: 18em; }
.vocab { grid-column: 1 / -1; display: flex; flex-wrap: wrap; align-items: center; gap: 0.35em; margin-top: 0.3em; }
.vchip { font-size: 0.9rem; padding: 0.05em 0.45em; border-radius: 0.3em; color: #111827; border: 1px solid #e5e7eb; }
.vchip.base { background: var(--ann-paper-raised); color: var(--ann-ink-soft); border-color: var(--ann-line); }
</style>
