<!--
  PosEncStrip - sinusoidal positional encoding, drawn two ways.

  Numbers come from composables/useDeckNumbers.ts (N.posenc), generated by
  scripts/verify-attention.py section 7.  IF A NUMBER HERE DISAGREES, THIS
  FILE IS WRONG.

    mode = 'strip'  positions (rows) x dimensions (columns), d = 16.
                    Each cell is a square whose AREA is |value| and whose hue
                    is its sign (teal +, ember -) - magnitude encoded twice,
                    as everywhere in the deck. Under each sin/cos pair: its
                    period, i.e. how many positions one turn of that "clock
                    hand" takes. Left columns spin fast (seconds hand), right
                    columns barely move (hours hand).
    mode = 'curve'  d = 512 (the real base model): similarity of position 20
                    to every position 0..40. Peak at itself, falling off with
                    distance - nearby positions look alike.

  CLICK CONTRACT: none.  Opacity only via :style.
-->

<script setup lang="ts">
import { computed } from 'vue'
import { N } from '../composables/useDeckNumbers'

const props = withDefaults(defineProps<{
  mode?: 'strip' | 'curve'
  highlightRow?: number
  rows?: number
  compact?: boolean
}>(), { mode: 'strip', compact: false })

const strip = computed(() => (N.posenc.strip as unknown as number[][]).slice(0, props.rows ?? 24))
const periods = N.posenc.periods as unknown as number[]
const sim = N.posenc.curve.similarity as unknown as number[]
const ref = N.posenc.curve.ref

const C = 22, LEFT = 64, TOP = 30
const d = N.posenc.dim
const SW = LEFT + d * C + 20
const SH = computed(() => TOP + strip.value.length * C + 26)

const fmtP = (p: number) => (p >= 1000 ? `${Math.round(p / 1000)}k` : p >= 100 ? `${Math.round(p)}` : p.toFixed(1))

// curve geometry
const CW = 760, CHh = 260, PL = 60, PB = 44, PT = 20
const cx = (i: number) => PL + (i / (sim.length - 1)) * (CW - PL - 20)
const cy = (v: number) => PT + (1 - (v - 0.5) / 0.5) * (CHh - PT - PB)
const path = sim.map((v, i) => `${i ? 'L' : 'M'} ${cx(i)} ${cy(v)}`).join(' ')
</script>

<template>
  <div class="pe" :class="{ 'is-compact': compact }">
    <svg v-if="mode === 'strip'" :viewBox="`0 0 ${SW} ${SH}`" xmlns="http://www.w3.org/2000/svg">
      <text :x="LEFT + (d * C) / 2" :y="14" class="axis">dimension &#8594; (sin, cos, sin, cos, …)</text>
      <g v-for="(row, r) in strip" :key="r">
        <text :x="LEFT - 8" :y="TOP + r * C + C / 2 + 4" class="pos" :class="{ lit: highlightRow === r }">{{ r }}</text>
        <rect v-for="(v, c) in row" :key="c"
              :x="LEFT + c * C + (C - (C - 3) * Math.sqrt(Math.abs(v))) / 2"
              :y="TOP + r * C + (C - (C - 3) * Math.sqrt(Math.abs(v))) / 2"
              :width="(C - 3) * Math.sqrt(Math.abs(v))" :height="(C - 3) * Math.sqrt(Math.abs(v))"
              :fill="v >= 0 ? 'var(--ann-circuit)' : 'var(--ann-ember)'"
              :style="{ opacity: 0.3 + 0.7 * Math.abs(v) }" />
        <rect v-if="highlightRow === r" :x="LEFT - 2" :y="TOP + r * C" :width="d * C + 4" :height="C"
              fill="none" stroke="var(--ann-indigo)" stroke-width="2.5" rx="3" />
      </g>
      <text :x="14" :y="TOP + (strip.length * C) / 2" class="axis"
            :transform="`rotate(-90 14 ${TOP + (strip.length * C) / 2})`">position</text>
      <text v-for="(p, i) in periods" :key="'p' + i"
            :x="LEFT + (2 * i + 1) * C" :y="TOP + strip.length * C + 18" class="per">{{ fmtP(p) }}</text>
    </svg>

    <svg v-else :viewBox="`0 0 ${CW} ${CHh}`" xmlns="http://www.w3.org/2000/svg">
      <line v-for="t in [0.5, 0.75, 1]" :key="t" :x1="PL" :x2="CW - 20" :y1="cy(t)" :y2="cy(t)"
            stroke="var(--ann-line)" stroke-width="1" />
      <text v-for="t in [0.5, 0.75, 1]" :key="'l' + t" :x="PL - 8" :y="cy(t) + 4" class="tick end">{{ t.toFixed(2) }}</text>
      <path :d="path" fill="none" stroke="var(--ann-circuit)" stroke-width="3" />
      <circle v-for="(v, i) in sim" :key="i" :cx="cx(i)" :cy="cy(v)" :r="i === ref ? 6 : 3"
              :fill="i === ref ? 'var(--ann-ember)' : 'var(--ann-circuit)'" />
      <text v-for="i in [0, 10, 20, 30, 40]" :key="'x' + i" :x="cx(i)" :y="CHh - PB + 18" class="tick">{{ i }}</text>
      <text :x="(PL + CW) / 2" :y="CHh - 6" class="axis">position (compared with position {{ ref }}, d = {{ N.posenc.curve.dim }})</text>
    </svg>
  </div>
</template>

<style scoped>
.pe svg { width: 100%; max-height: 56vh; display: block; margin: 0 auto; }
.pe.is-compact svg { max-height: 33vh; }
text { text-anchor: middle; font-family: 'JetBrains Mono', ui-monospace, monospace; }
.axis { font-size: 11px; fill: var(--ann-muted); letter-spacing: 0.04em; }
.pos { font-size: 12px; fill: var(--ann-ink-soft); text-anchor: end; }
.pos.lit { fill: var(--ann-indigo); font-weight: 700; }
.per { font-size: 11px; fill: var(--ann-indigo); font-weight: 600; }
.tick { font-size: 12px; fill: var(--ann-ink-soft); }
.tick.end { text-anchor: end; }
</style>
